version: '3.8'
services:
  api:
    build: .
    ports:
      - '8000:8000'
    env_file:
      - .env
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - '5432:5432'
